packages:
  - packages/*
  - demo
  - demo-next

allowBuilds:
  better-sqlite3: true
  esbuild: true
  sharp: true
  unrs-resolver: true

minimumReleaseAgeExclude:
  - prism-design-widget@0.1.1

onlyBuiltDependencies:
  - better-sqlite3
  - esbuild
  - sharp
  - unrs-resolver
