import * as DialogPrimitive from "@radix-ui/react-dialog";
import { Slot } from "@radix-ui/react-slot";
import { cva, type VariantProps } from "class-variance-authority";
import { clsx, type ClassValue } from "clsx";
import type { ButtonHTMLAttributes, ComponentPropsWithoutRef, HTMLAttributes, InputHTMLAttributes, ReactNode, TextareaHTMLAttributes } from "react";
import { twMerge } from "tailwind-merge";

export function cn(...inputs: ClassValue[]) { return twMerge(clsx(inputs)); }
const buttonVariants = cva("inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-md text-sm font-medium transition-all disabled:pointer-events-none disabled:opacity-50 [&_svg]:pointer-events-none [&_svg:not([class*='size-'])]:size-4 shrink-0 outline-none focus-visible:ring-[3px] focus-visible:ring-ring/50 cursor-pointer select-none", { variants: { variant: { default: "bg-primary text-primary-foreground hover:bg-primary/90", destructive: "bg-destructive text-white hover:bg-destructive/90", outline: "border border-input bg-background hover:bg-accent hover:text-accent-foreground", secondary: "bg-bg2 text-secondary-foreground hover:bg-secondary/80", ghost: "hover:bg-accent hover:text-accent-foreground" }, size: { default: "h-9 px-4 py-2", sm: "h-8 rounded-md px-3 text-xs", lg: "h-10 rounded-md px-6", icon: "size-9" } }, defaultVariants: { variant: "default", size: "default" } });
export { buttonVariants };
export interface ButtonProps extends ButtonHTMLAttributes<HTMLButtonElement>, VariantProps<typeof buttonVariants> { asChild?: boolean }
export function Button({ className, variant, size, asChild = false, ...props }: ButtonProps) { const Comp = asChild ? Slot : "button"; return <Comp data-slot="button" className={cn(buttonVariants({ variant, size }), className)} {...props} />; }
export function Input({ className, type, ...props }: InputHTMLAttributes<HTMLInputElement>) { return <input type={type} data-slot="input" className={cn("flex h-9 w-full rounded-md border border-input bg-white px-3 py-1 text-sm transition-colors file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-[3px] focus-visible:ring-ring/50 disabled:cursor-not-allowed disabled:opacity-50", className)} {...props} />; }
export function Badge({ className, variant = "default", ...props }: HTMLAttributes<HTMLSpanElement> & { variant?: "default" | "secondary" | "destructive" | "outline" }) { const styles = { default: "border-transparent bg-primary text-primary-foreground", secondary: "border-transparent bg-secondary text-secondary-foreground", destructive: "border-transparent bg-destructive text-white", outline: "text-foreground border-border" }; return <span data-slot="badge" className={cn("inline-flex w-fit shrink-0 items-center justify-center gap-1 overflow-hidden whitespace-nowrap rounded-md border px-2 py-0.5 text-xs font-semibold", styles[variant], className)} {...props} />; }
export function Separator({ className, orientation = "horizontal" }: { className?: string; orientation?: "horizontal" | "vertical" }) { return <div role="separator" className={cn("shrink-0 bg-border", orientation === "horizontal" ? "h-px w-full" : "h-full w-px", className)} />; }
export function SidePanelHeader({ title, leading, trailing }: { title: string; leading?: ReactNode; trailing?: ReactNode }) { return <header data-slot="sidepanel-header" className="flex items-center gap-1.5 border-b bg-card px-2 py-1.5"><div className="flex w-5 justify-center">{leading}</div><span className="font-semibold text-xs">{title}</span><div className="ml-auto">{trailing}</div></header>; }
export function MessageComposer({ beforeInput, actions, className, ...props }: TextareaHTMLAttributes<HTMLTextAreaElement> & { beforeInput?: ReactNode; actions?: ReactNode }) { return <section data-slot="message-composer" className={cn("space-y-1.5 border-t p-2", className)}>{beforeInput}<textarea className="min-h-[60px] max-h-[120px] w-full resize-none rounded-md border bg-background px-2.5 py-2 text-sm font-normal outline-none focus:ring-1 focus:ring-ring disabled:cursor-not-allowed disabled:opacity-50" rows={3} {...props} /><div className="flex justify-end gap-1">{actions}</div></section>; }
export const Dialog = DialogPrimitive.Root;
export const DialogTrigger = DialogPrimitive.Trigger;
export const DialogTitle = DialogPrimitive.Title;
export function DialogContent({ className, children, ...props }: ComponentPropsWithoutRef<typeof DialogPrimitive.Content>) { return <DialogPrimitive.Portal><DialogPrimitive.Overlay className="fixed inset-0 z-50 bg-black/35 backdrop-blur-[2px]" /><DialogPrimitive.Content className={cn("fixed left-1/2 top-1/2 z-50 w-[min(360px,calc(100vw-32px))] -translate-x-1/2 -translate-y-1/2 rounded-xl border bg-popover p-4 text-popover-foreground shadow-xl outline-none", className)} {...props}>{children}</DialogPrimitive.Content></DialogPrimitive.Portal>; }
